### ISSUE TITLE
getSortableTitle & unicode quotation marks

### ISSUE THREAD

**Issue by mtrojan-ub** [solrmarc/solrmarc#79]
It seems like getSortableTitle is removing simple kinds of quotation marks (like ' and ")

However, it would be nice if all unicode quotation marks would be removed.
see [Unicode Quotation Marks](https://unicode-table.com/en/sets/quotation-marks/)

**Comment by haschart** [comment]
The getSortableTitle method internally uses the specification modifier stripPunct  to strip all punctuation.   However as you noted "all punctuation" doesn't include all punctuation.   I have a relatively simple fix for this where instead of using:
        str.replaceAll("( |\\p{Punct})+", " ");
I construct a static Pattern like this:
        private static Pattern PUNCT_OR_SPACE = Pattern.compile("[ \\p{Punct}]+", Pattern.UNICODE_CHARACTER_CLASS);
which will match all Unicode Punctuation Marks including (as far as I can tell) all of the Unicode Quotation Marks that are listed in your link.   I'll push the changed file (FieldFormatterBase.java) soon and then close this issue.

**Comment by mtrojan-ub** [comment]
Thanks for your help! In the meantime we figured out that it might be a good idea to filter unicode characters for "…" and "¿" as well. It would be great if the pattern you mentioned also would cover these characters.

**Comment by haschart** [comment]
I just checked and the change I made will find and delete those punctuation marks as well.
